apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-conversaodetemperatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-conversaodetemperatura
  template:
    metadata:
      labels:
        app: web-conversaodetemperatura
    spec:
      containers:
        - name: web-conversaodetemperatura
          image: wallmed/conversao-temp:v1
          ports:
          - containerPort: 8080

---


apiVersion: v1
kind: Service
metadata:
  name: web-conversaodetemperatura
spec:
  selector:
    app: web-conversaodetemperatura
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
